{"uid":"e37d43f7ccfc8979","name":"test_dagbag_import_errors","fullName":"test_dags_general.TestDagsGeneral#test_dagbag_import_errors","historyId":"a2c30e60bd3adbfb3084f7c4abb839ff","time":{"start":1744704452643,"stop":1744704452643,"duration":0},"description":"\n        Test that there are no DAG import errors.\n        \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        ","descriptionHtml":"<pre><code>    Test that there are no DAG import errors.\n    \n    Import errors usually indicate syntax errors or missing dependencies\n    that prevent the DAG from being properly loaded.\n</code></pre>\n","status":"failed","statusMessage":"AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nassert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\n +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd3625bd340>.import_errors","statusTrace":"self = <test_dags_general.TestDagsGeneral object at 0x7fd3625aca30>\ndagbag = <airflow.models.dagbag.DagBag object at 0x7fd3625bd340>\n\n    def test_dagbag_import_errors(self, dagbag):\n        \"\"\"\n        Test that there are no DAG import errors.\n    \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        \"\"\"\n>       assert not dagbag.import_errors, f\"DAG import errors: {dagbag.import_errors}\"\nE       AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE       assert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE        +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd3625bd340>.import_errors\n\ntest_dags_general.py:88: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"dagbag","time":{"start":1744704452625,"stop":1744704452642,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"\n        Test that there are no DAG import errors.\n        \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        ","status":"failed","statusMessage":"AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nassert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\n +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd3625bd340>.import_errors","statusTrace":"self = <test_dags_general.TestDagsGeneral object at 0x7fd3625aca30>\ndagbag = <airflow.models.dagbag.DagBag object at 0x7fd3625bd340>\n\n    def test_dagbag_import_errors(self, dagbag):\n        \"\"\"\n        Test that there are no DAG import errors.\n    \n        Import errors usually indicate syntax errors or missing dependencies\n        that prevent the DAG from being properly loaded.\n        \"\"\"\n>       assert not dagbag.import_errors, f\"DAG import errors: {dagbag.import_errors}\"\nE       AssertionError: DAG import errors: {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE       assert not {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'}\nE        +  where {'/home/runner/work/2024-gitops-minicamp/2024-gitops-minicamp/airflow/dags/dbt_simple_task_group.py': 'Traceback (most recent call last):\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/converter.py\", line 256, in __init__\\n    project_config.validate_project()\\n  File \"/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/cosmos/config.py\", line 263, in validate_project\\n    raise CosmosValueError(f\"Could not find {name} at {path}\")\\ncosmos.exceptions.CosmosValueError: Could not find manifest at /opt/airflow/dbt-docs/manifest.json\\n'} = <airflow.models.dagbag.DagBag object at 0x7fd3625bd340>.import_errors\n\ntest_dags_general.py:88: AssertionError","steps":[],"attachments":[{"uid":"dcfc03a1e5759079","name":"log","source":"dcfc03a1e5759079.txt","type":"text/plain","size":5828}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"suite","value":"test_dags_general"},{"name":"subSuite","value":"TestDagsGeneral"},{"name":"host","value":"fv-az1914-625"},{"name":"thread","value":"3889-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_dags_general"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"e37d43f7ccfc8979.json","parameterValues":[]}